### ISSUE TITLE
Waves in model

### ISSUE THREAD

**Issue by zafarali** [CompuCell3D/CompuCell3D#11]
Hi there,

I had a quick question, when running models with the Mitosis and Growth plugin enabled, we observe "wave"-like phenomenon which resembles a bubble bursting somewhere and then propagating through the whole lattice. This especially happens if two cell types have slightly differing growth rates.

This even occurs in `clusterMitsosis.cc3d` 
![screen shot 2015-06-09 at 11 16 27 am](https://cloud.githubusercontent.com/assets/6295292/8061475/fc81bb38-0e98-11e5-8775-483d99aecd6d.png)

![image](https://cloud.githubusercontent.com/assets/6295292/8061659/e001a576-0e99-11e5-9d32-5d581158a542.png)

- sudden increase in # of cells at ≈6500MCS due to contraction
![screen shot 2015-06-09 at 11 22 21 am](https://cloud.githubusercontent.com/assets/6295292/8061669/f6a7ca4e-0e99-11e5-8200-2175ac4e7c29.png)

I was curious as to why this happens and if here is a tweak to fix it?

**Comment by maciekswat** [comment]
You need to make sure that right after the mitosis the target volume/surface parameters of the daughter cells (childCell in CC3D terminology) and  especially the parent cell are reset to the reasonable values. For example if your starting target volume of parent cell is 25 and mitosis happens when volume reaches 50 then in the updateAttributes functions you need to reset targetVolume to ~ 25 otherwise if you keep increasing targetVolume without resetting it then you will get unreasonably fast growth. . LEt me know if this answers your question

**Comment by zafarali** [comment]
That is what I am doing at the moment, and the issue seems to be suppressed. I will get back to you if the problem continues (possibly with animations)
