### ISSUE TITLE
DLL load failed error

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#23]
Hi,
I installed compucell3d -3.7.5 on windows 64 bit. When I run the player via cmd, I get this error:
"c://compucell3d/player/compucell3d.pyw line 9
import sip
DLL failed: The specified module couldn't be found"

It seems something is missing?

Thanks

**Comment by maciekswat** [comment]
What version if Windows are you running? Can you try installing 32 bit version and see if this works?
Maciek Swat,
Biocomplexity Institute
Phone:(812) 855_2441

On August 16, 2016, at 6:49 PM, nadaa <notifications@github.com> wrote:

Hi,
I installed compucell3d -3.7.5 on windows 64 bit. When I run the player via cmd, I get this error:
"c://compucell3d/player/compucell3d.pyw line 9
import sip
DLL failed: The specified module couldn't be found"

It seems something is missing?

Thanks 

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CompuCell3D/CompuCell3D","title":"CompuCell3D/CompuCell3D","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CompuCell3D/CompuCell3D">https://github.com/CompuCell3D/CompuCell3D</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"DLL load failed error (#23)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CompuCell3D/CompuCell3D/issues/23">https://github.com/CompuCell3D/CompuCell3D/issues/23</a>"}}}

**Comment by nadaa** [comment]
I have windows 7 sp1.
I Installed 32bi but still the problem exists!

**Comment by nadaa** [comment]
Shall I install minicoda & Numpy?

**Comment by maciekswat** [comment]
New packages are shipped with anaconda so you don’t need any external dependencies

Could you send me the output of “set path” - typed without quotes from the console from which you are trying to run CC3D. I wonder if you have other python/pyqt installations on your system that somehow cause conflicts





-- 
Maciej Swat

Biocomplexity Institute, Indiana University,

Simon Hall MSB1, 043D
212 S. Hawthorne Drive
Bloomington, IN  47405-7003

e-mail: mswat@indiana.edu
phone: (812) 855-2441
fax: (812) 855-5533

**Comment by nadaa** [comment]
C:\CompuCell3D>set path
Path=C:\CompuCell3D\lib\CompuCell3DSteppables;C:\CompuCell3D\lib\CompuCell3DPlug
ins;C:\CompuCell3D\lib\extralibs;C:\CompuCell3D\Python27;C:\CompuCell3D\bin;C:\P
rogram Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Win
dows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPow
erShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C
:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
 Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\In
tel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C
:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Lenovo\Finge
rprint Manager Pro\;C:\Program Files (x86)\Common Files\Lenovo;C:\Program Files
(x86)\Common Files\lenovo\easyplussdk\bin;C:\SWTOOLS\ReadyApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

**Comment by maciekswat** [comment]
Apparently this is known issue on windows. I have just installed fresh 
copy of Windows 7 SP1 and I get the same error - that sip's dll. cannot 
be found. The reason for that is that vs_2015 redistributable package 
fails to install on Windows 7 UNLESS you install other updates. Please 
see this instruction and

https://www.smartftp.com/support/kb/the-program-cant-start-because-api-ms-win-crt-runtime-l1-1-0dll-is-missing-f2702.html


Try following the above instructions and tell me if it works. I will do 
those updates myself and try to localize the exact problem

**Comment by nadaa** [comment]
Thanks maciekswat. I'm trying windows update, but that doesn't seem I can manage. checking for updates keep running forever!!

**Comment by maciekswat** [comment]
You may also try installing VisualStudio 2015 Community version ( free of charge)

https://www.visualstudio.com/

This is a big download but will get you all the dependencies and presumably includes fixes for the broken Windows Updater. 

Are you running CC3D on your laptop or inside virtual machine? Also if you have not registered your windows version yet you may get similar problems. There is also another way to fix the package but why don’t you try the above solution and let me know if it works. BTW I have the same problem on my freshly installed Windows 7 inside VMware virtual machine




-- 
Maciej Swat

Biocomplexity Institute, Indiana University,

Simon Hall MSB1, 043D
212 S. Hawthorne Drive
Bloomington, IN  47405-7003

e-mail: mswat@indiana.edu
phone: (812) 855-2441
fax: (812) 855-5533

**Comment by nadaa** [comment]
Thanks maciekswat. I will try that.
Shall I install the whole studio? Or I can customize installation?
I use CC3D on my laptop - my win is registered.

**Comment by CompuCell3D** [comment]
I think it is most important to install c++ component
-- 
Maciej Swat

Biocomplexity Institute, Indiana University,

Simon Hall MSB1, 043D
212 S. Hawthorne Drive
Bloomington, IN  47405-7003

e-mail: mswat@indiana.edu
phone: (812) 855-2441
fax: (812) 855-5533

**Comment by nadaa** [comment]
More than 3 hours past trying to install vs. Getting stuck in file"Hoxfix of windows KB2664825".
I'v tried twice.

**Comment by maciekswat** [comment]
It does take some time to install VS2015 but not sure if 3 hours is normal. Actually if you do not have ssd it my take easily about an hour. The most important thing is to make sure vs_redist_x64  is installed and this is what VS2015 will do - assuming it can  finish the install. 



-- 
Maciej Swat

Biocomplexity Institute, Indiana University,

Simon Hall MSB1, 043D
212 S. Hawthorne Drive
Bloomington, IN  47405-7003

e-mail: mswat@indiana.edu
phone: (812) 855-2441
fax: (812) 855-5533

**Comment by nadaa** [comment]
Hi Maciej,
Installing vs2015 doesn't work with me, An error interrupted the installation. I tried many times first with online mode then using vs iso image.

What alternative solutions you have?
Now, I have a fresh system - I reset it to the factory installation.
I do appreciate your collaboration!

Thanks

**Comment by maciekswat** [comment]
So I tried manually placing all dlls in the bin directory but this does 
not work. Clearly Microsoft did something strange to the update system 
because on my installation I canno install any updates. this is known 
problem aparently but non of the solutions posted online worked in my 
case. I am runnig windows in the emulator  though (I had no problems on 
a physical device)

Are you running CC3D on a physical laptop or in the emulator? NOt sure 
if I asked you this question?

**Comment by nadaa** [comment]
I've tested CC3D on my physical laptop with windows 7.
This issue took me much time, and I really want to move on in my work.
In case I install CC3D on virtual machine with linux os, how is the performance of CC3D  ?

What linux distro have you tried with CC3D?

Thank you!

**Comment by maciekswat** [comment]
Cc3d is the slowest on windows faster o. Linux and fastest on osx. The differences are small thoigh. I recommend ubuntu lts release 14.04, 16.04 . Make sure to install 64bit version. I am puzzled by windows 7 behavior. I tested cc3d on Windows 8.1 and 10 and it works fine. I will still try to resolve this issue

Maciek Swat,
Biocomplexity Institute
Phone:(812) 855_2441

On August 31, 2016, at 11:41 AM, nadaa <notifications@github.com> wrote:

I've tested CC3D on my physical laptop with windows 7.
This issue took me much time, and I really want to move on in my work.
In case I install CC3D on virtual machine with linux os, how is the performance of CC3D ?

What linux distro have you tried with CC3D?

Thank you!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CompuCell3D/CompuCell3D","title":"CompuCell3D/CompuCell3D","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CompuCell3D/CompuCell3D">https://github.com/CompuCell3D/CompuCell3D</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nadaa in #23: I've tested CC3D on my physical laptop with windows 7.\r\nThis issue took me much time, and I really want to move on in my work.\r\nIn case I install CC3D on virtual machine with linux os, how is the performance of CC3D ?\r\n\r\nWhat linux distro have you tried with CC3D?\r\n\r\nThank you!\r\n"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CompuCell3D/CompuCell3D/issues/23#issuecomment-243788214">https://github.com/CompuCell3D/CompuCell3D/issues/23#issuecomment-243788214</a>"}}}

**Comment by nadaa** [comment]
Then I will move to vm linux.
Thanks Maciek and good luck.
