### ISSUE TITLE
numpy failed-(linux)

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#24]
I installed cc3d v3.7.5 on linux by following the steps in http://www.compucell3d.org/SrcBin/LinuxCompile
When  I ran CC3D, a message shows that I should install numpy.
I tested the default python in the terminal, and imported numpy, it was there!

What can I do to resolve this issue?
Thanks

![cc3d-error](https://cloud.githubusercontent.com/assets/1457075/18168310/e5c358ba-7009-11e6-868a-81302b623483.png)

**Comment by maciekswat** [comment]
Did you install pyqwt using debian package or you comped it? It is o e of the dependencies. What linux distro did you choose? I think this has to do with pyqwt bug that is present in the bundled package. Let me know which distro you are using and I will send you location of the bug and how to fix it

Maciek Swat,
Biocomplexity Institute
Phone:(812) 855_2441

On September 1, 2016, at 9:05 AM, nadaa <notifications@github.com> wrote:

I installed cc3d v3.7.5 on linux by following the steps in http://www.compucell3d.org/SrcBin/LinuxCompile
When I ran CC3D, a message shows that I should install numpy.
I test the default python in the terminal, and imported numpy it was there!

What I can do to resolve this issue?
Thanks

￼

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CompuCell3D/CompuCell3D","title":"CompuCell3D/CompuCell3D","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CompuCell3D/CompuCell3D">https://github.com/CompuCell3D/CompuCell3D</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"numpy is not installed -linux (#24)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CompuCell3D/CompuCell3D/issues/24">https://github.com/CompuCell3D/CompuCell3D/issues/24</a>"}}}

**Comment by nadaa** [comment]
I use Ubuntu 16.04, and I installed all dependencies as shown for Debian based !

**Comment by maciekswat** [comment]
Here is the fix for PyQwt

1. Locate file on your machine

/usr/lib/python2.7/dist-packages/PyQt4/Qwt5/anynumpy.py

2. Replace it with the following content

# import either NumPy, or numarray, or Numeric

for name in ('numpy', 'numarray', 'Numeric'):
    failed = False
    try:
         eval(compile('from %s import *' % name, 'eval', 'exec'))
         if name == 'numpy':
             pass
             #from numpy.oldnumeric.compat import *
             #Float = float
             #UInt8 = uint8
    except ImportError:
        failed = True
    if not failed:
        break
else:
    import PyQt4.Qt as Qt
    if not Qt.QCoreApplication.instance():
        a = Qt.QApplication([])
    Qt.QMessageBox.critical(
        None,
        'Numerical Python Extension Required',
        'This example requires a Numerical Python Extension, but\n'
        'failed to import either NumPy, or numarray, or Numeric.\n'
        'NumPy is available at http://sourceforge.net/projects/numpy'
        )
    raise SystemExit(
        'Failed to import
ei/usr/lib/python2.7/dist-packages/PyQt4/Qwt5/anynumpy.pyther NumPy, or
numarray, or N
        'NumPy is available at http://sourceforge.net/projects/numpy'
        )

# Local Variables: ***
# mode: python ***
# End: ***

I am also attaching this file

Essentially what I have done I commented out obsolete 3 lines following line

if name=='numpy'

let me know if this works - if you edit this file manually watch for weird
indentation... I can send you the correct file by mail if you want

**Comment by CompuCell3D** [comment]
looks like you will need to manually edit the file - pasted version eliminated all the indents. 
-- 
Maciej Swat

Biocomplexity Institute, Indiana University,

Simon Hall MSB1, 043D
212 S. Hawthorne Drive
Bloomington, IN  47405-7003

e-mail: mswat@indiana.edu
phone: (812) 855-2441
fax: (812) 855-5533

**Comment by nadaa** [comment]
Thanks  lot Maciej.
That's really helpful- it works.

Regards
