### ISSUE TITLE
Simulation in 2.5D (z=2) doesn't do diffusion properlly when number of processors is set to 2

### ISSUE THREAD

**Issue by JulianoGianlupi** [CompuCell3D/CompuCell3D#297]
One of our workshop students found that bug while Josh was giving lecture 2.2. The user was using ubuntu 18.04. We did some debugging and the field was 0 at z=1 (not a rendering issue). On z=0 where the cells are and are secreting into diffusion happened as it should

Simulation used
[Module_2.2.Version2.zip](https://github.com/CompuCell3D/CompuCell3D/files/5030706/Module_2.2.Version2.zip)

![image](https://user-images.githubusercontent.com/35964356/89452154-3589a480-d72b-11ea-8c7d-f4e75192f8e3.png)

**Comment by CompuCell3D** [comment]
OK, after running CytokineSimulation from the attached bundle I could not replicate the bug. I noticed though that if you remove a plot window than the simulation may show some weird behavior. The fix is to remove _settings.sqllite from the simulation folder - effectively resetting settings for this simulation. Try and see if this works

**Comment by CompuCell3D** [comment]
It also looks like restarting player may help, i.e. when running new simulation simply restart Player

**Comment by JulianoGianlupi** [comment]
Fixed in #323
