### ISSUE TITLE
error in cc3d

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#30]
Hi,
I installed some python libraries, then cc3d didn't work properly!
This is the errors I receive 
![sc](https://cloud.githubusercontent.com/assets/1457075/20389953/30505686-ac81-11e6-840f-98bd03f6b9e1.png)

Note that( I have miniconda installed, when I change the default python to miniconda, cc3d doesn't work. How I can fix this?) I want to run my program and compucell3 simulation together?

How to resolve this?

Thanks

**Comment by maciekswat** [comment]
The vtk library is missing. Perhaps you uninstalled it while installing new packages.  How did you install these new packages and what were they?

Maciek Swat,
Biocomplexity Institute
Phone:(812) 855_2441

On November 17, 2016, at 7:46 AM, nadaa <notifications@github.com> wrote:

Hi,
I installed some python libiraries, then cc3d didn't work properly!
This is the errors I receive
￼

How to resolve this?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CompuCell3D/CompuCell3D","title":"CompuCell3D/CompuCell3D","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CompuCell3D/CompuCell3D">https://github.com/CompuCell3D/CompuCell3D</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"error in cc3d (#30)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CompuCell3D/CompuCell3D/issues/30">https://github.com/CompuCell3D/CompuCell3D/issues/30</a>"}}}

**Comment by nadaa** [comment]
The problem is that I have two python installed one is the default and the other is within miniconda. How can reconfigure CC3D such that it works with miniconda python?

Thanks

**Comment by maciekswat** [comment]
You will need to recompile CC3D. Not too difficult. Just make sure that in cmake python header, python library and executable are from miniconda distribution. This may require manual setting if the parhs

Maciek Swat,
Biocomplexity Institute
Phone:(812) 855_2441

On November 17, 2016, at 4:30 PM, nadaa <notifications@github.com> wrote:

The problem is that I have two python installed one is the default and the other is within miniconda. How can reconfigure CC3D such that it works with miniconda python?

Thanks

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CompuCell3D/CompuCell3D","title":"CompuCell3D/CompuCell3D","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CompuCell3D/CompuCell3D">https://github.com/CompuCell3D/CompuCell3D</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nadaa in #30: The problem is that I have two python installed one is the default and the other is within miniconda. How can reconfigure CC3D such that it works with miniconda python?\r\n\r\nThanks"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CompuCell3D/CompuCell3D/issues/30#issuecomment-261375669">https://github.com/CompuCell3D/CompuCell3D/issues/30#issuecomment-261375669</a>"}}}

**Comment by nadaa** [comment]
Ok, I will try.
Shall I install PyQt (with OpenGL modules)  into miniconda?

Thanks

**Comment by maciekswat** [comment]
Yes and you will need to build qscintilla from source because for some crazy reason conda does not ship with qscintilla 

Maciek Swat,
Biocomplexity Institute
Phone:(812) 855_2441

On November 18, 2016, at 4:03 PM, nadaa <notifications@github.com> wrote:

Ok, I will try.
Shall I install PyQt (with OpenGL modules) into miniconda?

Thanks

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CompuCell3D/CompuCell3D","title":"CompuCell3D/CompuCell3D","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CompuCell3D/CompuCell3D">https://github.com/CompuCell3D/CompuCell3D</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nadaa in #30: Ok, I will try.\r\nShall I install PyQt (with OpenGL modules) into miniconda?\r\n\r\nThanks\r\n\r\n"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CompuCell3D/CompuCell3D/issues/30#issuecomment-261641187">https://github.com/CompuCell3D/CompuCell3D/issues/30#issuecomment-261641187</a>"}}}
