### ISSUE TITLE
Save simulation running as a video

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#33]
Hi,
Is there any option incc3d  to record model progress and save it as a video format?

Thanks

**Comment by CompuCell3D** [comment]
Not directly. The best thing right now is to save vtk lattice files, replay them later in the Player to generate .png images and then use 3rd party software to generate movies. I can post here hints how to accomplish this on various platforms. Let me know if this would be helpful



On December 6, 2016, at 2:36 PM, nadaa <notifications@github.com> wrote:

Hi,
Is there any option incc3d to record model progress and save it as a video format?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CompuCell3D/CompuCell3D","title":"CompuCell3D/CompuCell3D","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CompuCell3D/CompuCell3D">https://github.com/CompuCell3D/CompuCell3D</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Save simulation running as a video (#33)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CompuCell3D/CompuCell3D/issues/33">https://github.com/CompuCell3D/CompuCell3D/issues/33</a>"}}}

**Comment by CompuCell3D** [comment]
Regarding model progress - what exactly are you hoping to accomplish? Could you give me an example ?

On December 6, 2016, at 2:36 PM, nadaa <notifications@github.com> wrote:

Hi,
Is there any option incc3d to record model progress and save it as a video format?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CompuCell3D/CompuCell3D","title":"CompuCell3D/CompuCell3D","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CompuCell3D/CompuCell3D">https://github.com/CompuCell3D/CompuCell3D</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Save simulation running as a video (#33)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CompuCell3D/CompuCell3D/issues/33">https://github.com/CompuCell3D/CompuCell3D/issues/33</a>"}}}

**Comment by tjsego** [comment]
Stale. Closing.
