### ISSUE TITLE
Access SimFileName, if Thread is of Type CMLFieldHandler ? (executed by runScript.bat)

### ISSUE THREAD

**Issue by MasterKarinski** [CompuCell3D/CompuCell3D#35]
If you execute cc3d python scripts by opening the cc3d files in  the GUI version of Compucell, the variable "simthread" will be an instance of `Simulation.Simulationthread`. 

This way you are able to access the methods of `SimulationThread.py`, for example `getSimFileName()`, to identify the path of the executed cc3d file.

If you run the same file using the runSim.bat, the instance of simthread will be of CMLFieldHandler.CMLFieldHandler and this class has other methods available. If you call the method  `simFileName=self.simthread.getSimFileName()` this will cause python to crash without further logging.

I added this code to my python setup:
```
 def __init__(self, sim, simthread):
        print "Simthread:",simthread
```
 
Output if you run the script from compucell GUI:
`Simthread: <Simulation.SimlationThread.SimulationThread object at 0x04BD1030>
`
Output if you run the script from runScript.bat:

```
Simthread: <CMLFieldHandler.CMLFieldHandler instance at 0x0369B5A8>
```

This is how I start the runscript.bat file:
```
.\runScript.bat -i "C:\Users\Myuser\Documents\compucellmodels\SpaSdbCdiInDa\1485109855769\runJson.cc3d" -f 10000
```

EDIT: 
This is how I initialize the Compucell3d Setup.

```
import sys
from os import environ

import CompuCellSetup
sys.path.append(environ["PYTHON_MODULE_PATH"])

sim, simthread = CompuCellSetup.getCoreSimulationObjects()

# Now load the model to simulate!
from ModuroModel.Sd.JsonBasedModelDa import JsonBasedModelDa
model = JsonBasedModelDa(sim, simthread)
print "Model initialized. Running simulation...."
model._run()
```

I have to identify the path of the current cc3d file to load a matching configuration file, which is always located in the same directory as the cc3d file. Each cc3d file refers to the same python script, so I cannot use static paths.

Is there a way to receive the path of the  current cc3d file, if you execute the cc3d-file by the runScript.bat?

Is there something like a parameter map you can access for each simulation, which also includes this info?

Sincerly

Karin

**Comment by maciekswat** [comment]
Karin

You can do this like that:

Inside your steppable type:

sim_filename = CompuCellSetup.simulationFileName


Let me know if this solves your problem

What other information about running simulation would you like to have 
programmatic access to?

**Comment by MasterKarinski** [comment]
Hi,

actually this did not work:
```

import sys
from os import environ

import CompuCellSetup
sys.path.append(environ["PYTHON_MODULE_PATH"])

sim, simthread = CompuCellSetup.getCoreSimulationObjects()
print "RunJsoncc3d:",CompuCellSetup.simulationFileName

# Now load the model to simulate!
from ModuroModel.Sd.JsonBasedModelDa import JsonBasedModelDa
model = JsonBasedModelDa(sim, simthread)
print "Model initialized. Running simulation...."
model._run()

```

output: 
`"RunJsoncc3d:"`

**Comment by maciekswat** [comment]
Can you send me the simplified version of your .cc3d project? Also, what version of cc3d are you running and what is the OS?


On January 29, 2017, at 10:39 AM, MasterKarinski <notifications@github.com> wrote:

Hi,

actually this did not work:

import sys from os import environ import CompuCellSetup sys.path.append(environ["PYTHON_MODULE_PATH"]) sim, simthread = CompuCellSetup.getCoreSimulationObjects() print "RunJsoncc3d:",CompuCellSetup.simulationFileName # Now load the model to simulate! from ModuroModel.Sd.JsonBasedModelDa import JsonBasedModelDa model = JsonBasedModelDa(sim, simthread) print "Model initialized. Running simulation...." model._run() 

output:
"RunJsoncc3d:"

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CompuCell3D/CompuCell3D","title":"CompuCell3D/CompuCell3D","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CompuCell3D/CompuCell3D">https://github.com/CompuCell3D/CompuCell3D</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MasterKarinski in #35: Hi,\r\n\r\nactually this did not work:\r\n```\r\n\r\nimport sys\r\nfrom os import environ\r\n\r\nimport CompuCellSetup\r\nsys.path.append(environ[\"PYTHON_MODULE_PATH\"])\r\n\r\nsim, simthread = CompuCellSetup.getCoreSimulationObjects()\r\nprint \"RunJsoncc3d:\",CompuCellSetup.simulationFileName\r\n\r\n# Now load the model to simulate!\r\nfrom <a href="http://ModuroModel.Sd">ModuroModel.Sd</a>.JsonBasedModelDa import JsonBasedModelDa\r\nmodel = JsonBasedModelDa(sim, simthread)\r\nprint \"Model initialized. Running simulation....\"\r\nmodel._run()\r\n\r\n```\r\n\r\noutput: \r\n`\"RunJsoncc3d:\"`"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CompuCell3D/CompuCell3D/issues/35#issuecomment-275921808">https://github.com/CompuCell3D/CompuCell3D/issues/35#issuecomment-275921808</a>"}}}

**Comment by MasterKarinski** [comment]
My bad - I executed the cc3d file in gui mode. If you run the `compucell3d.bat` and then open the cc3d file like this F`ile -> Open Simulation File (cc3d)`, you will not be able to access  `CompuCellSetup.simulationFileName
`
I just started the cc3d file using the `runScript.bat` and I was able to retrieve the value. I did not change my python code.
But this means my project can only be executed in console mode. How can you access the filepath when you execute the simulation in gui mode?

Maybe it's possible to refactor the CompuCellSetup class so there will be a static context.

My cc3d File:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Simulation version="3.7.4">
    <PythonScript Type="Python">C:\Users\MyUser\Idea\Moduro-CC3D\Simulation\RunJsonCc3D.py</PythonScript>
</Simulation>
```

**Comment by CompuCell3D** [comment]
This is really strange because I have just run a simulation with the following steppable
```
from PySteppables import *
import CompuCell
import CompuCellSetup
import sys
from random import randint, random
from math import sin, cos, pi

class RandomMotionSteppable(SteppableBasePy):    

    def __init__(self,_simulator,_frequency=1):
        SteppableBasePy.__init__(self,_simulator,_frequency)
        
    def step(self,mcs):        
        print 'simulation file name = ', CompuCellSetup.simulationFileName

```

and I get the correct output using both GUI and runScript.bat
```
Step 205 Flips 757/10000 Energy -3780.21 Cells 192 Inventory=192
simulation file name =  d:\CC3DProjects\RandomMotion\RandomMotion.cc3d
FAST numberOfAttempts=10000
Number of Attempted Energy Calculations=1584
Step 206 Flips 768/10000 Energy -3717.25 Cells 192 Inventory=192
simulation file name =  d:\CC3DProjects\RandomMotion\RandomMotion.cc3d
FAST numberOfAttempts=10000
Number of Attempted Energy Calculations=1572
Step 207 Flips 779/10000 Energy -3396.25 Cells 192 Inventory=192
simulation file name =  d:\CC3DProjects\RandomMotion\RandomMotion.cc3d
```

What OS /CC3D version are you running?

**Comment by tjsego** [comment]
Stale. Closing.
